### ISSUE TITLE
Return seat when starting a newparty

### ISSUE THREAD

**Issue by nbeguier** [ConstanceMorel/Tarot_Learner#2]
Ajouter la valeur 'id' lors du retour de la commande GET /newparty.
Cet id sera la place du joueur qui a démarré la nouvelle partie. Si possible, il faudrait que ce soit 0.

**Comment by ConstanceBeguier** [comment]
*** Pushed ***

commit 5bed661d91bc329684b6cd3766b24946da02a06a
Author: MOREL Constance <constance.morel@novencia.com>

Date:   Sat May 6 12:15:39 2017 +0200

    return seat when starting a new party
