### ISSUE TITLE
Order card when returned

### ISSUE THREAD

**Issue by nbeguier** [ConstanceMorel/Tarot_Learner#3]
Si possible, lors de la requête /hand/:id, il faudrait que les cartes retournées soient hiérarchisées par couleurs.

**Comment by ConstanceBeguier** [comment]
Done

commit c6dc36e47da7267b2dcbcbf0c66b748a249adb02
Author: MOREL Constance <constance.morel@novencia.com>
Date:   Sat May 6 12:10:27 2017 +0200

    API: /hand/id returns ordered cards
